version: "3.9"
services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: .docker/Dockerfile
    image: laravel
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - mynetwork
    volumes:
      - ./:/var/www
    working_dir: /var/www/

  mysql:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - mynetwork

  redis:
    image: redis:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
